// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_SECRET_ROLE_KEY = import.meta.env.VITE_SECRETROLE;

// Validate environment variables with better error messages
if (!SUPABASE_URL) {
  const error = new Error(
    "Missing VITE_SUPABASE_URL environment variable. Please check your .env file.",
  );
  console.error(error.message);
  throw error;
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  const error = new Error(
    "Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable. Please check your .env file.",
  );
  console.error(error.message);
  throw error;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

// Admin client with service role key (bypasses RLS)
// Use this for operations that require elevated permissions
// WARNING: Only use this client for server-side operations or when you need to bypass RLS
export const supabaseAdmin = SUPABASE_SECRET_ROLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_SECRET_ROLE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    })
  : null;
